---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json
environment_name: "minikube"

DOCKER_IO: "docker.io"
K8S_GCR_IO: "k8s.gcr.io"
GHCR_IO: "ghcr.io"
QUAY_IO: "quay.io"
minikube: "registry.digitalocean.com/licenta-registry"
# minikube: "srp.minikube.com:5000"

SMTP_FROM_ADDRESS: "ioachim.lihor@gmail.com"

tcpforwards:
  "5672": "default/rabbitmq:5672"
  "8080": "default/predicter:8080"
  "27017": "default/mongodb:27017"
  "15672": "default/rabbitmq:15672"
  "6379": "default/redis-headless:6379"
  "9093": "default/prometheus-alertmanager:9093"
