---
mongodb:
  host: mongodb
  port: 27017
  username: root
  password: "ikkgIzSjBW"

celery:
  broker_url: "amqp://admin:3oUb5ZlIIm@rabbitmq:5672//"
  expires_multiplier: 1.5
  task_ignore_result: true
  task_store_errors_even_if_ignored: true
  task_track_started: false
  result_extended: false
  broker_pool_limit: 256

redis:
  host: "redis-master"
  port: 6379

site:
  - url: "https://www.timesnewroman.ro/"
    type: "news"
    routes:
      - "politic/"
      - "sport/"
      - "life-death/"
      - "it-stiinta/"
      - "monden/"
  - url: "https://www.biziday.ro/"
    type: "news"
    routes: []
  - url: "https://www.biziday.ro/feed"
    type: "rss"
    routes: []
  - url: "https://www.digi24.ro/"
    type: "news"
    routes:
      - "stiri/actualitate/politica"
      - "stiri/actualitate"
      - "stiri/economie"
      - "stiri/externe"
      - "stiri/sport"
      - "stiri/sci-tech"
