---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  timeout: 600
  skipDeps: true
  historyMax: 2

missingFileHandler: Error

environments:
  default:
    values:
      - ../tags.yaml
      - ../config.yaml
      - ../infra_env.yaml

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

---
releases:
  - name: grafana
    chart: bitnami/grafana
    version: 7.9.1
    values:
    - image:
        name: "{{ .Values.DOCKER_IO }}/grafana/grafana"
        tag: "{{ .Values.GRAFANA_TAG }}"
        pullPolicy: IfNotPresent
    - persistence:
        enable: true
    - ingress:
        enabled: true
        hostname: {{ tpl "grafana.aa.{{ .Values.environment_name }}.com" . }}
    - grafana:
        replicaCount: 1
        extraEnvVars:
        - name: GF_SERVER_DOMAIN
          value: {{ tpl "grafana.aa.{{ .Values.environment_name }}.com" . }}
        - name: GF_SERVER_PROTOCOL
          value: "http"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s/"
        - name: GF_LOG_MODE
          value: "console"
        - name: GF_LOG_LEVEL
          value: "debug"
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_HOST
          value: "email-smtp:25"
        - name: GF_SMTP_FROM_ADDRESS
          value: "{{ .Values.SMTP_FROM_ADDRESS }}"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_DEFAULT_THEME
          value: "dark"

  - name: predicter
    chart: ../predicter-chart
    namespace: default
    values:
    - image:
        name: "{{ .Values.minikube }}/predicter"
        tag: 1.0.0
        pullPolicy: Always
    - ingress:
        enabled: true
        hostname: {{ tpl "licenta.lihor.ro" . }}

  - name: celery-beat
    chart: ../celery-beat-chart
    namespace: default
    values:
    - image:
        name: "{{ .Values.minikube }}/celery-beat"
        tag: "1.0.0"
        pullPolicy: Always
    - config:
        celery: {{- toYaml $.Values.celery | nindent 10 }}
        mongodb: {{- toYaml $.Values.mongodb | nindent 10 }}
        site: {{- toYaml $.Values.site | nindent 10 }}


  - name: celery-scrapper
    chart: ../celery-scrapper-chart
    namespace: default
    values:
    - image:
        name: "{{ .Values.minikube }}/celery-scrapper"
        tag: "1.0.0"
        pullPolicy: Always
    - config:
        celery: {{- toYaml $.Values.celery | nindent 10 }}
        mongodb: {{- toYaml $.Values.mongodb | nindent 10 }}
        redis: {{- toYaml $.Values.redis | nindent 10 }}


  - name: celery-searcher
    chart: ../celery-searcher-chart
    namespace: default
    values:
    - image:
        name: "{{ .Values.minikube }}/celery-searcher"
        tag: "1.0.0"
        pullPolicy: Always
    - config:
        celery: {{- toYaml $.Values.celery | nindent 10 }}
        mongodb: {{- toYaml $.Values.mongodb | nindent 10 }}
        redis: {{- toYaml $.Values.redis | nindent 10 }}

  - name: celery-completer
    chart: ../celery-completer-chart
    namespace: default
    values:
    - image:
        name: "{{ .Values.minikube }}/celery-completer"
        tag: "1.0.0"
        pullPolicy: Always
    - config:
        celery: {{- toYaml $.Values.celery | nindent 10 }}
        mongodb: {{- toYaml $.Values.mongodb | nindent 10 }}
        redis: {{- toYaml $.Values.redis | nindent 10 }}

  - name: celery-similarity
    chart: ../celery-similarity-chart
    namespace: default
    values:
    - image:
        name: "{{ .Values.minikube }}/celery-similarity"
        tag: "1.0.0"
        pullPolicy: Always
    - config:
        celery: {{- toYaml $.Values.celery | nindent 10 }}
        mongodb: {{- toYaml $.Values.mongodb | nindent 10 }}
        redis: {{- toYaml $.Values.redis | nindent 10 }}

  - name: restapi-content-predicter
    chart: ../restapi-content-predicter-chart
    namespace: default
    values:
    - image:
        name: "{{ .Values.minikube }}/restapi-content-predicter"
        tag: 1.0.0
        pullPolicy: Always
    - ingress:
        enabled: false
        hostname: "restapi-content-predicter.minikube.com"
    - config:
        listen:
          host: "0.0.0.0"
          port: 80
    - replicaCount: 1

  - name: restapi-title-predicter
    chart: ../restapi-title-predicter-chart
    namespace: default
    values:
    - image:
        name: "{{ .Values.minikube }}/restapi-title-predicter"
        tag: 1.0.0
        pullPolicy: Always
    - ingress:
        enabled: false
        hostname: "restapi-title-predicter.minikube.com"
    - config:
        listen:
          host: "0.0.0.0"
          port: 80
    - replicaCount: 1
