{{- if .Values.ingress.enabled }}
{{- if gt (int .Capabilities.KubeVersion.Minor) 18 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: "{{ .Values.ingress.ingressClassName }}"
  rules:
  - host: "{{ .Values.ingress.hostname }}"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.service.port }}
{{- else }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: "{{ .Values.ingress.ingressClassName }}"
  rules:
  - host: "{{ .Values.ingress.hostname }}"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: {{ .Release.Name }}
            servicePort: {{ .Values.service.port }}
{{- end }}
{{- end }}
