{
 "title": "Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "minikube",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"minikube\"}"
    }
   ]
  },
  {
   "title": "Prometheus AlertManager",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"alertmanager\"}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"grafana\"}"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{app=\"mongodb\"}"
    }
   ]
  }
 ]
}