---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  timeout: 600
  skipDeps: true
  historyMax: 2

missingFileHandler: Error

environments:
  default:
    values:
      - ../tags.yaml
      - ../config.yaml
      - ../infra_env.yaml

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

---
releases:
  - name: mongodb
    # chart: https://github.com/bitnami/charts/tree/master/bitnami/mongodb
    # history:
    # https://artifacthub.io/packages/helm/bitnami/mongodb/13.8.1
    # https://charts.bitnami.com/bitnami/mongodb-13.8.1.tgz
    chart: bitnami/mongodb
    version: 13.8.1
    values:
      - image:
          registry: "{{ .Values.DOCKER_IO }}"
          repository: bitnami/mongodb
          tag: "{{ .Values.MONGODB_TAG }}"
          debug: true
      - architecture: "standalone"
      - useStatefulSet: true
      - auth:
          rootUser: root
          rootPassword: "ikkgIzSjBW"
      - enableIPv6: true
      - systemLogVerbosity: 0
      - disableSystemLog: true
      - persistence:
          size: 8Gi
      - volumePermissions:
          enabled: true
          image:
            registry: "{{ .Values.DOCKER_IO }}"
            repository: "bitnami/bitnami-shell"
            tag: "{{ .Values.BITNAMI_SHELL_TAG }}"
            pullPolicy: IfNotPresent
      - terminationGracePeriodSeconds: 120
      - livenessProbe:
          enabled: true
          timeoutSeconds: 55
          periodSeconds: 60
          failureThreshold: 3
          successThreshold: 1
      - readinessProbe:
          enabled: true
          timeoutSeconds: 55
          periodSeconds: 60
          failureThreshold: 3
          successThreshold: 1
      - metrics:
          enabled: false
          image:
            registry: "{{ .Values.DOCKER_IO }}"
            repository: "bitnami/mongodb-exporter"
            tag: "{{ .Values.MONGODB_EXPORTER_TAG }}"
          serviceMonitor:
            enabled: false
          prometheusRule:
            enabled: false
  - name: rabbitmq
    # chart: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
    # history: https://github.com/bitnami/charts/commits/master/bitnami/rabbitmq
    # https://artifacthub.io/packages/helm/bitnami/rabbitmq/11.10.0
    # https://charts.bitnami.com/bitnami/rabbitmq-11.10.0.tgz
    chart: bitnami/rabbitmq
    version: 11.10.0
    values:
      - image:
          registry: "{{ .Values.DOCKER_IO }}"
          repository: "bitnami/rabbitmq"
          tag: "{{ .Values.RABBITMQ_TAG }}"
          debug: true
          pullPolicy: IfNotPresent
      - auth:
          username: admin
          password: 3oUb5ZlIIm
          erlangCookie: "mysecretcookie"
      - replicaCount: 1
      - persistence:
          enabled: true
          accessMode: ReadWriteOnce
      - service:
          port: 5672
          portName: amqp
      - volumePermissions:
          enabled: true
          image:
            registry: "{{ .Values.DOCKER_IO }}"
            repository: "bitnami/bitnami-shell"
            tag: "{{ .Values.BITNAMI_SHELL_TAG }}"
      - ingress:
          enabled: true
          path: "/"
          hostname: "rabbitmq.minikube.com"
      - extraConfiguration: |-
          collect_statistics_interval = 10000
          consumer_timeout = 31622400000

  # chart: https://github.com/bitnami/charts/tree/master/bitnami/redis
  # history: https://github.com/bitnami/charts/commits/master/bitnami/redis
  # https://artifacthub.io/packages/helm/bitnami/redis/17.8.0
  # https://charts.bitnami.com/bitnami/redis-17.8.0.tgz
  - name: redis
    chart: bitnami/redis
    version: 17.8.0
    values:
      - image:
          registry: "{{ .Values.DOCKER_IO }}"
          repository: bitnami/redis
          tag: "{{ .Values.REDIS_TAG }}"
      - architecture: standalone
      - auth:
          enabled: false
          sentinel: false
      - persistence:
          enabled: true
      - replica:
          replicaCount: 1
      - volumePermissions:
          enabled: true
          image:
            registry: "{{ .Values.DOCKER_IO }}"
            repository: bitnami/bitnami-shell
            tag: "{{ .Values.BITNAMI_SHELL_TAG }}"
            pullPolicy: IfNotPresent
