# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  timeout: 600
  skipDeps: true
  historyMax: 2

missingFileHandler: Error

environments:
  default:
    values:
      - ../tags.yaml
      - ../config.yaml
      - ../infra_env.yaml

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mongodb
    # chart: https://github.com/bitnami/charts/tree/master/bitnami/mongodb
    # history:
    # https://artifacthub.io/packages/helm/bitnami/mongodb/11.0.3
    # https://charts.bitnami.com/bitnami/mongodb-11.0.3.tgz
    chart: bitnami/mongodb
    version: 11.0.3
    values:
    - image:
        registry: "{{ .Values.DOCKER_IO }}"
        repository: bitnami/mongodb
        tag: "{{ .Values.MONGODB_TAG }}"
        debug: true
    - architecture: "standalone"
    - useStatefulSet: true
    - auth:
        rootPassword: "123456"
    - enableIPv6: true
    - systemLogVerbosity: 0
    - disableSystemLog: true
    - persistence:
        size: 8Gi
    - volumePermissions:
        enabled: true
        image:
          registry: "{{ .Values.DOCKER_IO }}"
          repository: "bitnami/bitnami-shell"
          tag: "{{ .Values.BITNAMI_SHELL_TAG }}"
          pullPolicy: IfNotPresent
    - terminationGracePeriodSeconds: 120
    - livenessProbe:
        enabled: true
        timeoutSeconds: 55
        periodSeconds: 60
        failureThreshold: 3
        successThreshold: 1
    - readinessProbe:
        enabled: true
        timeoutSeconds: 55
        periodSeconds: 60
        failureThreshold: 3
        successThreshold: 1
    - metrics:
        enabled: true
        image:
          registry: "{{ .Values.DOCKER_IO }}"
          repository: "bitnami/mongodb-exporter"
          tag: "{{ .Values.MONGODB_EXPORTER_TAG }}"
        serviceMonitor:
          enabled: false
        prometheusRule:
          enabled: false
  - name: rabbitmq
    # chart: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
    # history: https://github.com/bitnami/charts/commits/master/bitnami/rabbitmq
    # https://artifacthub.io/packages/helm/bitnami/rabbitmq/8.29.0
    # https://charts.bitnami.com/bitnami/rabbitmq-8.29.0.tgz
    chart: bitnami/rabbitmq
    version: 8.29.0
    values:
    - image:
        registry: {{ .Values.DOCKER_IO }}
        repository: "bitnami/rabbitmq"
        tag: {{ .Values.RABBITMQ_TAG }}
        debug: true
        pullPolicy: IfNotPresent
    - auth:
        username: admin
        password: 3oUb5ZlIIm
    - replicaCount: 1
    - persistence:
        enabled: true
        accessMode: ReadWriteOnce
    - service:
        port: 5672
        portName: amqp
    - volumePermissions:
        enabled: true
        image:
          registry: {{ .Values.DOCKER_IO }}
          repository: "bitnami/bitnami-shell"
          tag: {{ .Values.BITNAMI_SHELL_TAG }}
    - ingress:
        enabled: true
        path: "/"
        hostname: "rabbitmq"
